#####
# SIMPAGER Makefile
#####

target: list of dependencies
	cmd 1
	cmd 2
	cmd 3
	...

target2: list of dependencies
	cmd 1
	cmd 2
	...

target3: list of dependencies
	cmd 1
	etc
	...

target4:
	cmds
